on:
  release:
    types: [published]

name: Build Release Artifacts

jobs:
  #1
  build-macos:
    name: Build macOS Executable
    #2
    runs-on: macos-latest
    steps:
      #3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build macOS binary
        run: scripts/build-universal-macos.sh
      #4
      - name: "Upload macOS Build Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ProjectAnalyzer-macos
          path: builds/ProjectAnalyzer-macos
  build-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build it
        run: scripts/build-linux.sh
      - name: "Upload Linux Build Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ProjectAnalyzer-linux
          path: builds/ProjectAnalyzer-linux
  #1
  upload:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    #2
    needs: [build-macos, build-linux]
    #3
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      #4
      - name: List downloaded files
        run: ls -R
      #5
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.name }}
          files: ./*/*
          fail_on_unmatched_files: true
